# name: Manual Deployment

# on:
#   workflow_dispatch:
#     inputs:
#       reason:
#         description: 'Reason for deployment'
#         required: false
#         default: 'Manual update'

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Build and Restart PrismAPI
#         run: |
#           echo "Deploying for: ${{ github.event.inputs.reason }}"
#           docker compose up --build -d
#           docker image prune -f

#       - name: Healthcheck
#         run: |
#           echo "Starting progressive Healthcheck..."
#           for i in {1..10}; do
#             # On tente de joindre l'API via le Gateway (Nginx)
#             if curl --fail --silent http://localhost/v1/system > /dev/null; then
#               echo "✅ Service is Ready (Attempt $i/10)."
#               exit 0
#             fi
#             echo "⚠️ Attempt $i/10: Service not ready yet — waiting 5s..."
#             sleep 5
#           done
#           echo "❌ Healthcheck failed after 50s. Checking logs..."
#           docker compose logs api-service
#           exit 1